### ISSUE TITLE
make dist fails

### ISSUE THREAD

**Issue by enlf-dev** [ferdymercury/amide#18]
I hoped to send 1.0.6 source distributions along side the windows installers, however any variant of 'make dist' currently fails with some errors. 
 
... lots of "undefined references" like

```
C:/BUILD/amide64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\BUILD\amide64\home\ewn\project\amide\amide-current\doc\reference/amitk-scan.c:121: undefined reference to `amitk_object_dialog_get_type'

... ending in ...
make[6]: *** [Makefile:807: scan-build.stamp] Error 1
make[6]: Leaving directory '/home/ewn/project/amide/amide-current/doc/reference'
make[5]: *** [Makefile:619: distdir] Error 2
make[5]: Leaving directory '/home/ewn/project/amide/amide-current/doc/reference'
make[4]: *** [Makefile:533: distdir-am] Error 1
...
```

**Comment by ferdymercury** [comment]
Did you solve the issue? If yes, how? Thanks!

**Comment by ferdymercury** [comment]
In Ubuntu18, with flag --disable-doc, I get this error:

```
/usr/bin/ld: ../../src/dcmtk_interface.o: undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by ferdymercury** [comment]
The following workaround deactivating gtkdoc works for me:

```
git clean -xfd
cd amide-current
intltoolize
libtoolize
gnome-doc-prepare
touch gtk-doc.make
autoreconf --install
./configure
make
make dist
```

**Comment by ferdymercury** [comment]
hmm can you try removing line 21 https://github.com/ferdymercury/amide/blob/main/amide-current/Makefile.am#L21 and see if it works then?

**Comment by enlf-dev** [comment]
No, it didn't work. Same failures. The doc/README is clear that it doesn't built well as of 2012 when libdcmdata support was configured in. 

What is more: clean start and disabling libdcmdata even breaks the linking of amide.exe ... with the same "undefined reference to" errors related to the libdcmdata (dcmtk) library.

**Comment by enlf-dev** [comment]
Trashing all libs to dcmtk still insists on linking -ldcmimage, -ldcmjpeg -lijg8 and so on.
I believe the crux must be there. The libdcmdata isn't totally disabled via the configure.

**Comment by enlf-dev** [comment]
After some tweaking I can get a sources tgz file. However, it can't be used to build. Bails out with an error: "No rule to make target 'align_pt.h' which seems to be missing in pixmaps.
Can your tgz sources file be used to build?

**Comment by ferdymercury** [comment]
Same issue here, it was broken.

I think it should be fixed with: https://github.com/ferdymercury/amide/commit/605b9d997be8ea6a3121ae53020ec663eea29967

**Comment by ferdymercury** [comment]
For msys2, can you try now with:
https://github.com/ferdymercury/amide/tree/win32
?

Thanks

**Comment by ferdymercury** [comment]
Thanks for https://github.com/ferdymercury/amide/pull/20#event-6824083196

Does it finish now or are there new problems?

**Comment by enlf-dev** [comment]
A 'make dist' now does creates a compilable tgz file. The prerequisites for creating a tgz file are (1) docs enabled and (2) libdcmdata disabled.

A 'make distclean' however breaks a rebuild: for example pixmaps/*.h files are deleted. Will open that as another issue?

**Comment by ferdymercury** [comment]
Thanks for checking! Yes, a separate issue for distclean would be convenient.

**Comment by ferdymercury** [comment]
I guess this was solved by https://github.com/ferdymercury/amide/commit/605b9d997be8ea6a3121ae53020ec663eea29967 and https://github.com/ferdymercury/amide/pull/20
