### ISSUE TITLE
build fails in Fedora 33

### ISSUE THREAD

**Issue by martrs** [ferdymercury/amide#5]
when _autoreconf -i_ runs, it fails with README not found'. I had to rename README.md as README to make it work.

Also, ld linking causes multiple definitions of dummy_voxel. I had to define dummy_voxel in src/render.c then declare it extern in src/render.h.

**Comment by ferdymercury** [comment]
concerning autoreconf, instead of renaming the README, can you try to replace in your configure.ac this:
AM_INIT_AUTOMAKE with AM_INIT_AUTOMAKE([foreign]) as suggested here: https://github.com/Opendigitalradio/qt-drmplus/issues/3

**Comment by ferdymercury** [comment]
concerning dummy_voxel feel free to provide a Pull Request.
Thanks!

**Comment by ferdymercury** [comment]
A patch for the dummy voxel issue was suggested here https://sourceforge.net/p/amide/mailman/amide-users/thread/CAMW%3DR%3D%3DR0AkqB1zbV1Wp7PUK77EHMR%2BDONOyPZt%3Dc%2BR7_U11jQ%40mail.gmail.com/#msg37637584

**Comment by ferdymercury** [comment]
> when _autoreconf -i_ runs, it fails with README not found'. I had to rename README.md as README to make it work.

A link between README and README.md is now present, that should fix it.
 
> Also, ld linking causes multiple definitions of dummy_voxel. I had to define dummy_voxel in src/render.c then declare it extern in src/render.h.

This has been fixed upstream.
